[project]
name = "obdschat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.9"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "fastapi>=0.141.1",
    "gradio>=6.22.0",
    "httpx>=0.28.1",
    "lxml>=6.1.1",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "uvicorn>=0.52.1",
    "xmlschema>=4.3.2",
]
