"""Generate the committed REST API schema from the FastAPI application."""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Final

from backend.app import app

PROJECT_ROOT: Final = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_PATH: Final = (
    PROJECT_ROOT / "docs" / "developer" / "reference" / "openapi.json"
)


def serialize_openapi_schema() -> str:
    """Return deterministic JSON generated by the FastAPI application."""
    return (
        json.dumps(
            app.openapi(),
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )


def openapi_schema_is_current(output_path: Path = DEFAULT_OUTPUT_PATH) -> bool:
    """Return whether a generated schema matches the current application."""
    try:
        current_content = output_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return False
    return current_content == serialize_openapi_schema()


def write_openapi_schema(output_path: Path = DEFAULT_OUTPUT_PATH) -> bool:
    """Write the generated schema when changed and report whether it changed."""
    content = serialize_openapi_schema()
    try:
        if output_path.read_text(encoding="utf-8") == content:
            return False
    except FileNotFoundError:
        pass

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return True


def main(argv: Sequence[str] | None = None) -> int:
    """Generate the schema or verify that the committed schema is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when the generated schema is out of date",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Generated OpenAPI JSON destination",
    )
    arguments = parser.parse_args(argv)

    if arguments.check:
        if openapi_schema_is_current(arguments.output):
            print(f"OpenAPI schema is current: {arguments.output}")
            return 0
        print(
            f"OpenAPI schema is out of date: {arguments.output}. Run 'make docs-api'.",
            file=sys.stderr,
        )
        return 1

    changed = write_openapi_schema(arguments.output)
    state = "Generated" if changed else "Unchanged"
    print(f"{state} OpenAPI schema: {arguments.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
